#!/bin/bash

## Description: Install Drupal site for local development.
## Aliases: si
## Usage: site-install
## Example: "ddev site-install"
## ExecRaw: true

cd "$DDEV_COMPOSER_ROOT" || exit

# Install Drupal
drush site-install \
    --account-pass=admin \
    --site-name="Canvas CC SSR Sandbox"

# Enable modules
drush pm:enable -y canvas_cc_ssr

# Create a Canvas page.
# drush php:eval "\Drupal::service('entity_type.manager')->getStorage('canvas_page')->create(['title' => 'Home', 'path' => ['alias' => '/home']])->save();"
