#!/bin/bash

## Description: Install Drupal site for local development.
## Aliases: si
## Usage: site-install
## Example: "ddev site-install"
## ExecRaw: true

cd "$DDEV_COMPOSER_ROOT" || exit

# Install Drupal
drush site-install \
    --account-pass=admin \
    --site-name="xBrew Render Sandbox"

# Enable modules
drush pm:enable -y xbrew_render

# Create an XB page.
drush php:eval "\Drupal::service('entity_type.manager')->getStorage('xb_page')->create(['title' => 'Home', 'path' => ['alias' => '/home']])->save();"
